# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: 'default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'lib/**/*.csproj'
  
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**\*.MvcCore.csproj'
    versioningScheme: 'off'
    includeSymbols: true
      
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget push -s http://jagc-az-devops1:8080/v3/index.json $(Build.ArtifactStagingDirectory)/*.nupkg --api-key USAF_JAGC_SYMBOLS_SECRET'

